# Generated by Django 4.2.8 on 2024-07-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activation',
            field=models.BooleanField(default=True),
        ),
    ]
