# Generated by Django 4.2.8 on 2024-08-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_activation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
    ]
