# Generated by Django 4.2.8 on 2024-10-26 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_session_key_cart_hashed_session_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='hashed_session_key',
            new_name='session_key',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_session_key',
        ),
    ]
