# Generated by Django 4.2.8 on 2024-11-18 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 3, 5, 38, 502524, tzinfo=datetime.timezone.utc)),
        ),
    ]
