# Generated by Django 4.2.8 on 2024-11-18 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 3, 7, 37, 339539, tzinfo=datetime.timezone.utc)),
        ),
    ]
