# Generated by Django 4.2.8 on 2024-11-18 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 23, 21, 14, 634597, tzinfo=datetime.timezone.utc)),
        ),
    ]
