# Generated by Django 4.2.8 on 2024-11-27 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_order_expires_at_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 4, 26, 19, 843900, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['id', 'user', 'session_key'], name='store_cart_id_7c1b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='store_carti_cart_id_1ecc31_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='store_order_order_i_ec571c_idx'),
        ),
    ]
