# Generated by Django 4.2.8 on 2024-12-06 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_cart_store_cart_id_7c1b6a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 6, 4, 17, 58, 292388, tzinfo=datetime.timezone.utc)),
        ),
    ]
