# Generated by Django 4.2.8 on 2024-12-06 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 4, 20, 16, 199511, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
