# Generated by Django 4.2.8 on 2024-12-06 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 6, 4, 21, 1, 458138, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
