from rest_framework import status

EXPECTED_STATUS_CODES = {
    'anon': {
        'product': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_401_UNAUTHORIZED,
            'PUT': status.HTTP_401_UNAUTHORIZED,
            'PATCH': status.HTTP_401_UNAUTHORIZED,
            'DELETE': status.HTTP_401_UNAUTHORIZED,
        },
        'comment': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_401_UNAUTHORIZED,
            'PUT': status.HTTP_401_UNAUTHORIZED,
            'PATCH': status.HTTP_401_UNAUTHORIZED,
            'DELETE': status.HTTP_401_UNAUTHORIZED,
        },
        'cart': {
            'OPTIONS': status.HTTP_401_UNAUTHORIZED,
            'GET': status.HTTP_401_UNAUTHORIZED,
            'POST': status.HTTP_401_UNAUTHORIZED,
            'PUT': status.HTTP_401_UNAUTHORIZED,
            'PATCH': status.HTTP_401_UNAUTHORIZED,
            'DELETE': status.HTTP_401_UNAUTHORIZED,
        },
        'cartitems': {
            'OPTIONS': status.HTTP_401_UNAUTHORIZED,
            'GET': status.HTTP_401_UNAUTHORIZED,
            'POST': status.HTTP_401_UNAUTHORIZED,
            'PUT': status.HTTP_401_UNAUTHORIZED,
            'PATCH': status.HTTP_401_UNAUTHORIZED,
            'DELETE': status.HTTP_401_UNAUTHORIZED,
        },
        'customer': {
            'OPTIONS': status.HTTP_401_UNAUTHORIZED,
            'GET': status.HTTP_401_UNAUTHORIZED,
            'POST': status.HTTP_401_UNAUTHORIZED,
            'PUT': status.HTTP_401_UNAUTHORIZED,
            'PATCH': status.HTTP_401_UNAUTHORIZED,
            'DELETE': status.HTTP_401_UNAUTHORIZED,
        },
        'customer_info': {
            'OPTIONS': status.HTTP_401_UNAUTHORIZED,
            'GET': status.HTTP_401_UNAUTHORIZED,
            'POST': status.HTTP_401_UNAUTHORIZED,
            'PUT': status.HTTP_401_UNAUTHORIZED,
            'PATCH': status.HTTP_401_UNAUTHORIZED,
            'DELETE': status.HTTP_401_UNAUTHORIZED,
        },
        'address': {
            'OPTIONS': status.HTTP_401_UNAUTHORIZED,
            'GET': status.HTTP_401_UNAUTHORIZED,
            'POST': status.HTTP_401_UNAUTHORIZED,
            'PUT': status.HTTP_401_UNAUTHORIZED,
            'PATCH': status.HTTP_401_UNAUTHORIZED,
            'DELETE': status.HTTP_401_UNAUTHORIZED,
        },
        'order': {
            'OPTIONS': status.HTTP_401_UNAUTHORIZED,
            'GET': status.HTTP_401_UNAUTHORIZED,
            'POST': status.HTTP_401_UNAUTHORIZED,
            'PUT': status.HTTP_401_UNAUTHORIZED,
            'PATCH': status.HTTP_401_UNAUTHORIZED,
            'DELETE': status.HTTP_401_UNAUTHORIZED,
        },
        'payment': {
            'OPTIONS': status.HTTP_401_UNAUTHORIZED,
            'GET': status.HTTP_401_UNAUTHORIZED,
            'POST': status.HTTP_401_UNAUTHORIZED,
            'PUT': status.HTTP_401_UNAUTHORIZED,
            'PATCH': status.HTTP_401_UNAUTHORIZED,
            'DELETE': status.HTTP_401_UNAUTHORIZED,
        },
    },
    'user': {
        'product': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_403_FORBIDDEN,
            'PUT': status.HTTP_403_FORBIDDEN,
            'PATCH': status.HTTP_403_FORBIDDEN,
            'DELETE': status.HTTP_403_FORBIDDEN,
        },
        'comment': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_403_FORBIDDEN,
            'PUT': status.HTTP_403_FORBIDDEN,
            'PATCH': status.HTTP_403_FORBIDDEN,
            'DELETE': status.HTTP_403_FORBIDDEN,
        },
        'cart': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_201_CREATED,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'cartitems': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'customer': {
            'OPTIONS': status.HTTP_403_FORBIDDEN,
            'GET': status.HTTP_403_FORBIDDEN,
            'POST': status.HTTP_403_FORBIDDEN,
            'PUT': status.HTTP_403_FORBIDDEN,
            'PATCH': status.HTTP_403_FORBIDDEN,
            'DELETE': status.HTTP_403_FORBIDDEN,
        },
        'customer_info': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_405_METHOD_NOT_ALLOWED,
            'PUT': status.HTTP_200_OK,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            'DELETE': status.HTTP_405_METHOD_NOT_ALLOWED,
        },
        'address': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_200_OK,
            'DELETE': status.HTTP_403_FORBIDDEN,
        },
        'order': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_403_FORBIDDEN,
            'PATCH': status.HTTP_403_FORBIDDEN,
            'DELETE': status.HTTP_403_FORBIDDEN,
        },
        'payment': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_405_METHOD_NOT_ALLOWED,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            'DELETE': status.HTTP_405_METHOD_NOT_ALLOWED,
        },
    },
    'manager': {
        'product': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_200_OK,
            'DELETE': status.HTTP_405_METHOD_NOT_ALLOWED,
        },
        'comment': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_200_OK,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'cart': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_201_CREATED,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'cartitems': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'customer': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_405_METHOD_NOT_ALLOWED,
            'PUT': status.HTTP_200_OK,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            'DELETE': status.HTTP_405_METHOD_NOT_ALLOWED,
        },
        'customer_info': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_405_METHOD_NOT_ALLOWED,
            'PUT': status.HTTP_200_OK,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            'DELETE': status.HTTP_405_METHOD_NOT_ALLOWED,
        },
        'address': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_200_OK,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'order': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_200_OK,
            'PATCH': status.HTTP_200_OK,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'payment': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_405_METHOD_NOT_ALLOWED,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            'DELETE': status.HTTP_405_METHOD_NOT_ALLOWED,
        },
    },
    'admin': {
        'product': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_200_OK,
            'DELETE': status.HTTP_405_METHOD_NOT_ALLOWED,
        },
        'comment': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_200_OK,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'cart': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_201_CREATED,
            'PUT': status.HTTP_405_METHOD_NOT_ALLOWED,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'cartitems': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'customer': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_405_METHOD_NOT_ALLOWED,
            'PUT': status.HTTP_200_OK,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            'DELETE': status.HTTP_405_METHOD_NOT_ALLOWED,
        },
        'customer_info': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_405_METHOD_NOT_ALLOWED,
            'PUT': status.HTTP_200_OK,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            'DELETE': status.HTTP_405_METHOD_NOT_ALLOWED,
        },
        'address': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_400_BAD_REQUEST,
            'PATCH': status.HTTP_200_OK,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'order': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_200_OK,
            'PATCH': status.HTTP_200_OK,
            # 'DELETE': status.HTTP_204_NO_CONTENT,
        },
        'payment': {
            'OPTIONS': status.HTTP_200_OK,
            'GET': status.HTTP_200_OK,
            'POST': status.HTTP_400_BAD_REQUEST,
            'PUT': status.HTTP_405_METHOD_NOT_ALLOWED,
            'PATCH': status.HTTP_405_METHOD_NOT_ALLOWED,
            'DELETE': status.HTTP_405_METHOD_NOT_ALLOWED,
        },
    }
}
